
# tap repositories and their packages

tap homebrew/core
brew amazon-ecs-cli
brew ansible
brew autoconf
brew awscli
brew cabextract
brew curl
brew gdbm
brew gettext
brew git
brew go
brew jemalloc
brew libevent
brew libidn2
brew libssh
brew libtermkey
brew libunistring
brew libuv
brew libvterm
brew libyaml
brew luajit
brew mas
brew msgpack
brew neovim
brew openssl
brew pcre
brew pkg-config
brew python
brew python@2
brew readline
brew sphinx-doc
brew sqlite
brew tmate
brew tmux
brew tree
brew unibilium
brew unrar
brew wget
brew watch
brew xz
brew zsh

# Select files
brew fd

# Docker inspector
brew dive

# CLI File manager
brew ranger

brew pngcrush
brew hugo

brew mongodb
brew node

tap homebrew/cask-fonts
cask font-inconsolata
cask font-inconsolata-dz-for-powerline
cask font-inconsolata-g-for-powerline
cask font-menlo-for-powerline
cask font-source-code-pro-for-powerline

tap homebrew/cask
cask google-chrome
cask sublime-text
cask alacritty
cask libreoffice
cask obs

tap dteoh/sqa
cask slowquitapps

tap rcmdnk/file
brew brew-file

# Other Cask applications
cask font-inconsolata-dz
cask font-inconsolata-for-powerline
cask font-inconsolata-lgc
cask font-source-code-pro
cask gitup
cask google-hangouts

