tabspaces: 4
background_opacity: 0.98
draw_bold_text_with_bright_colors: true

dpi:
  x: 200.0
  y: 200.0

env:
  TERM: xterm-256color

window:
  padding:
    x: 2
    y: 2

  dynamic_padding: true
  decorations: full
  gtk_theme_variant: dark

scrolling:
  history: 10000
  multiplier: 3
  auto_scroll: false

colors:
  # Default colors
  primary:
    background: '#2c2c2c'
    foreground: '#f8f8f2'

  # Normal colors
  normal:
    black:   '#000000'
    red:     '#ff5555'
    green:   '#50fa7b'
    yellow:  '#f1fa8c'
    blue:    '#caa9fa'
    magenta: '#ff79c6'
    cyan:    '#8be9fd'
    white:   '#bfbfbf'

  # Bright colors
  bright:
    black:   '#575b70'
    red:     '#ff6e67'
    green:   '#5af78e'
    yellow:  '#f4f99d'
    blue:    '#caa9fa'
    magenta: '#ff92d0'
    cyan:    '#9aedfe'
    white:   '#e6e6e6'

font:
  normal:
    family: Fira Code 
    style: Medium

  bold:
    family: Fira Code
    style: Bold

  italic:
    family: Fira Code
    style: Italic

  size: 9

  offset:
    x: 0
    y: 0

  glyph_offset:
    x: 0
    y: 0

  use_thin_strokes: false

mouse:
  hide_when_typing: true

selection:
  semantic_escape_chars: ",│`|:\"' ()[]{}<>"
  save_to_clipboard: true

mouse_bindings:
  - { mouse: Middle, action: PasteSelection }

