tabspace: 4
custom_cursor_colors: true
live_config_reload: true
hide_cursor_when_typing: true

opacity: 0.1
env:
  TERM: xterm-256color

fonts:
  size: 12

colors:
  primary:
    background: '0x000000'
    foreground: '0xffffff'
  cursor:
    text:   '0xf1c1c1'
    cursor: '0xff2600'

shell:
  program: /usr/local/bin/zsh
  args:
    - --login
