dpi:
  x: 200.0
  y: 200.0

tabspaces: 4

env:
  TERM: xterm-256color

window:
  padding:
    x: 5
    y: 5

  dynamic_padding: false
  decorations: full
  gtk_theme_variant: dark

scrolling:
  history: 10000
  multiplier: 3
  auto_scroll: false

colors:
  primary:
    background: '0x2d2d2d'
    foreground: '0xabb2bf'

  normal:
    black:   '0x282c34'
    red:     '0xe06c75'
    green:   '0x839601'
    yellow:  '0xd19a66'
    blue:    '0x61afef'
    magenta: '0xc678dd'
    cyan:    '0x2AA198'
    white:   '0xabb2bf'

  bright:
    black:   '0x5c6370'
    red:     '0xe06c75'
    green:   '0x839601'
    yellow:  '0xd19a66'
    blue:    '0x61afef'
    magenta: '0xc678dd'
    cyan:    '0x2AA198'
    white:   '0xffffff'

font:
  normal:
    family: Fira Code Medium

  bold:
    family: Fira Code Medium

  italic:
    family: Fira Code Medium

  size: 9

  offset:
    x: 0
    y: 0

  glyph_offset:
    x: 0
    y: 0

  use_thin_strokes: false

draw_bold_text_with_bright_colors: false

visual_bell:
  animation: EaseOutExpo
  color: '0xffffff'
  duration: 0

background_opacity: 0.98

mouse:
  hide_when_typing: true

selection:
  semantic_escape_chars: ",│`|:\"' ()[]{}<>"
  save_to_clipboard: true

mouse_bindings:
  - { mouse: Middle, action: PasteSelection }
