tap "1password/tap"
tap "cockroachdb/tap"
tap "damascenorafael/tap"
tap "espanso/espanso"
tap "gitguardian/tap"
tap "hashicorp/tap"
tap "heroku/brew"
tap "homebrew/bundle"
tap "homebrew/cask-fonts"
tap "homebrew/services"
tap "lencx/chatgpt", "https://github.com/lencx/ChatGPT.git"
tap "ngrok/ngrok"
tap "suzuki-shunsuke/tfcmt"

brew "amazon-ecs-cli"
brew "awscli"

brew "fzf"
brew "exa"

brew "xz"
brew "libtiff"
brew "little-cms2"
brew "webp"
brew "jpeg-xl"
brew "cffi"
brew "freetype"
brew "openjpeg"
brew "openssl@1.1"
brew "libffi"
brew "libmagic"
brew "libpq"
brew "libxmlsec1"
brew "libyaml"
brew "libavif"
brew "gnutls"
brew "graphicsmagick"
brew "zlib"
brew "imagemagick"

brew "curl"
brew "wget"
brew "deno"
brew "direnv"
brew "duckdb"
brew "git"
brew "git-filter-repo"
brew "git-gui"
brew "graphviz"

brew "hey"
brew "htop"
brew "hugo"

brew "infracost"
brew "inframap"
brew "jq"
brew "mysql-client"
brew "neovim"
brew "nvm"
brew "optipng"
brew "pandoc"
brew "pipx"
brew "pnpm"
brew "virtualenv"
brew "pre-commit"
brew "pyenv"
brew "pygobject3"

brew "starship"

brew "terraform"
brew "terraform-docs"
brew "tflint"

brew "tmate"
brew "tmux"
brew "tree"

brew "heroku/brew/heroku"

cask "1password"
cask "appcleaner"
cask "barrier"
cask "blender"
cask "chatgpt"
cask "chromedriver"
cask "dbeaver-community"
cask "discord"
cask "docker"
cask "dropbox"
cask "easy-move-plus-resize"
cask "espanso"
cask "figma"

cask "font-dejavu-sans-mono-nerd-font"
cask "font-droid-sans-mono-nerd-font"
cask "font-fira-code-nerd-font"
cask "font-fira-mono-nerd-font"
cask "font-inconsolata-go-nerd-font"
cask "font-inconsolata-nerd-font"
cask "font-jetbrains-mono-nerd-font"
cask "font-liberation-nerd-font"
cask "font-noto-nerd-font"
cask "font-roboto-mono-nerd-font"
cask "font-space-mono-nerd-font"

cask "google-chrome"
cask "google-drive"

cask "hashicorp-vagrant"
cask "imageoptim"

cask "microsoft-auto-update"
cask "microsoft-excel"
cask "microsoft-powerpoint"
cask "microsoft-word"

cask "ngrok"
cask "postman"

cask "qlcolorcode"
cask "qlmarkdown"
cask "qlprettypatch"
cask "quicklook-csv"
cask "quicklook-json"

cask "raycast"
cask "rectangle"
cask "reminders-menubar"
cask "spotify"
cask "sublime-text"
cask "vimr"
cask "virtualbox"
cask "visual-studio-code"
cask "vlc"
cask "zoom"

