#!/usr/bin/env bash

tdir="/media/mariocesar/Toshiba 500 GB"
sdir="/media/mariocesar/5ba824e3-da2e-4253-b0dd-0e940832ec2f/mariocesar"

rsync -aAXrl --info=progress2 \
    --cvs-exclude \
    --exclude={"env","venv",".env","*.pyc","/lost+found"} \
    --exclude={"var",".vagrant",".idea",".cache"} \
    --exclude={"cmake","build"} \
    --exclude={"node_modules","static/vendors","public/media","public/static"} \
    ${sdir}/Documentos \
    ${sdir}/Dropbox \
    ${sdir}/Imágenes \
    ${sdir}/Libros \
    ${sdir}/Proyectos \
    ${sdir}/Videos \
    "${tdir}"
