#!/usr/bin/env bash
set -eux

sudo apt autoremove
sudo apt clean

journalctl --disk-usage
sudo journalctl --vacuum-time=7d
journalctl --disk-usage

du -sh ~/.cache/thumbnails ||:
rm -fr ~/.cache/thumbnails

docker volume prune -f
docker container prune -f
docker image prune -f
