#!/usr/bin/python
import gi
import sys
import urllib2

gi.require_version('Gtk', '3.0')

from gi.repository import Gtk


def ping_url(url):
    response = urllib2.urlopen(url)
    return response.getcode() == 200


sites = (
    'https://rascanube.com.bo/',
    'https://vevende.com/',
)


class Application(Gtk.Application):
    def do_activate(self):
        builder = Gtk.Builder()
        builder.add_from_file('daily-briefing.glade')
        builder.connect_signals({
            'on_run_button_clicked': self.handle_run_button_clicked
        })

        headerbar = builder.get_object('headerbar')

        window = builder.get_object('window')
        window.set_titlebar(headerbar)
        self.add_window(window)

        window.show_all()

    def handle_run_button_clicked(self, *args):
        print('click!!!')

        for url in sites:
            print(ping_url(url))
        

    def do_shutdown(self):
        print('Apagado!')

if __name__ == '__main__':
    application = Application()
    application.run(sys.argv)