#!/usr/bin/env bash 
set -e

SCALING_FACTOR=$(gsettings get org.gnome.desktop.interface scaling-factor | cut -d" " -f2)

if [ $SCALING_FACTOR = 2 ]; then
    gsettings set org.gnome.desktop.interface scaling-factor 1
else
    gsettings set org.gnome.desktop.interface scaling-factor 2
fi

